feat: SignIn Page + Add SCSS
egoryan8/memory-game pull request #2
Opened 2023-08-21 03:36 UTC by thevolkov

Страница авторизации + SCSS

2023-08-21 16:17 UTC, egoryan8 requested changes

2023-08-21 16:17 UTC, egoryan8 commented on packages/client/src/components/Input/types.ts
> +import { ChangeEvent } from 'react'
А нужно ли нам здесь типы выносить в отдельный файл? Это будет где-то использоваться еще?

2023-08-21 16:17 UTC, egoryan8 commented on packages/client/src/components/Input/types.ts
> +export default interface CInputProps {
Я думаю, что лучше хранить интерфейс компонента внутри компонента, если нам больше нигде не нужен этот интерфейс.

Первым делом, когда я открываю компонент я хочу увидеть его интерфейс, чтобы понять быстро что там за пропсы, а не идти и открывать где-то другой файл.

2023-08-21 16:17 UTC, egoryan8 commented on packages/client/src/components/Input/Input.tsx
> +const Input: React.FC<CInputProps> = ({
Вот здесь сразу не понятно какие типы у пропсов, а если бы сверху рядом был интерфейс, то было бы удобнее (основное замечание ниже)

2023-08-21 16:17 UTC, egoryan8 commented on packages/client/src/components/Input/types.ts
> +export interface InputValue {
Тот же вопрос - нужен ли нам этот интерфейс где-то еще? Если нет, давайте лучше утащим его внутрь компонента, для удобства.

2023-08-21 16:17 UTC, egoryan8 commented on packages/client/src/assets/styles/variables.scss
> +/* Sizes */
Круто, что вынес основные переменны!

2023-08-21 16:17 UTC, egoryan8 commented on packages/client/vite.config.ts
> +    alias: {
Круто, что добавил элиасы!

2023-08-21 20:24 UTC, thevolkov commented on packages/client/src/components/Input/types.ts
> +import { ChangeEvent } from 'react'
Ну это реактовые стандартные типы для событий. Я их не выносил, а уже переиспользую

2023-08-22 01:58 UTC, iterrait commented on packages/client/src/assets/styles/variables.scss
> +$base-blue: #1E85E4;
Предлагаю использовать переменные вида $color-primary, $color-secondary, $base-color, $main-color, тогда если потребуется сделать темы или менять цветовые схемы, то достаточно будет только поменять цвета без рефакторинга

2023-08-22 01:58 UTC, iterrait commented on packages/client/src/pages/Login/Login.tsx
> +        <a className="display-block" href="#">
Роутинг добавлен, давай добавим ссылку на регистрацию

2023-08-22 01:59 UTC, thevolkov commented on packages/client/src/pages/Login/Login.tsx
> +        <a className="display-block" href="#">
А кстати, да) Сделаю щас

2023-08-22 02:26 UTC, iterrait approved these changes

2023-08-22 07:34 UTC, aip-webdev approved these changes

2023-08-22 11:57 UTC, merged