feat: MEM-41 Add basic game logic
egoryan8/memory-game pull request #20
Opened 2023-09-03 17:38 UTC by thevolkov

### Задача: https://linear.app/memory-game/issue/MEM-41/sozdat-mehaniku-igry-na-canvas-api

- Реализована основная логика игры по поиску пар у карточек
- Добавлено отображение Эмодзи у открытых карточек (Заменить на иконки)
- Добавлено уведомление о победе
- Добавлена логика предварительного показа карточек перед началом игры
- Отображение курсора Pointer при наведении на карточку

### Требуется добавить:
- Добавить анимацию переворота карточек
- Добавить логику перезапуска игры после победы или проигрыша
- Добавить таймер игры

2023-09-04 09:18 UTC, aip-webdev approved these changes

2023-09-04 09:27 UTC, egoryan8 approved these changes

2023-09-05 17:48 UTC, Olegas requested changes
Добрый день.
Есть замечания по коду. 
Судя по всему есть ошибки в логике реализации.
Изложил свои соображения в отдельном комментарии (про таймауты)

2023-09-05 17:48 UTC, Olegas commented on packages/client/src/pages/Game/Game.tsx
> +  ctx.fillText(emoji, x + 40, y + 80)
40 и 80 - волшебные числа (magic numbers). Почему именно 40 и 80? Что это за значения? Почему они такие? Лучше завести константы, дать им понятные названия и использовать их тут.

2023-09-05 17:48 UTC, Olegas commented on packages/client/src/pages/Game/Game.tsx
> +    setCards(rows.flat())
Для чего делать сложную структуру (массив массивов) если затем она все равно превращается в плоский массив? Почему бы сразу просто не добавлять элементы в этот плоский массив?

2023-09-05 17:48 UTC, Olegas commented on packages/client/src/pages/Game/Game.tsx
> +  }, [canvasRef])
Кажется в зависимости от canvasRef нет смысла, ведь сам ref никогда не меняется (меняется только его значение, которое лежит в current)

2023-09-05 17:48 UTC, Olegas commented on packages/client/src/pages/Game/Game.tsx
> +    cards.forEach(card => {
Этот перебор - отличная работа для Array.prototype.some - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/some
И читается по проще, и весь массив пробегать не надо (остановится на первом попавшем под условие)

2023-09-05 17:48 UTC, Olegas commented on packages/client/src/pages/Game/Game.tsx
> +        }, 1000)
В коде много таймаутов, из-за которых скорее всего будут ошибки. Рассмотрим такой случай - я могу быстро накликать несколько карточек, больше двух, хоть все, и они все откроются. Я все это смогу сделать до наступления таймаута, который закрывает карточки. В итоге карточки, что я накликал после первых двух, не будут закрыты, так и останутся открытыми. Я думаю если поискать, найдется еще таких случаев когда во время ожидания таймера можно делать действия, которые не будут корректно обработаны

2023-09-05 19:25 UTC, thevolkov commented on packages/client/src/pages/Game/Game.tsx
> +        }, 1000)
Убрал таймер.

2023-09-05 19:25 UTC, thevolkov commented on packages/client/src/pages/Game/Game.tsx
> +    cards.forEach(card => {
Заменил.

2023-09-05 19:25 UTC, thevolkov commented on packages/client/src/pages/Game/Game.tsx
> +  }, [canvasRef])
Убрал. Старая логика.

2023-09-05 19:26 UTC, thevolkov commented on packages/client/src/pages/Game/Game.tsx
> +    setCards(rows.flat())
Осталось от старой логики. Убрал.

2023-09-05 19:26 UTC, thevolkov commented on packages/client/src/pages/Game/Game.tsx
> +  ctx.fillText(emoji, x + 40, y + 80)
Поправил.

2023-09-05 19:27 UTC, thevolkov commented
Замечания поправил.

2023-09-06 14:47 UTC, Olegas approved these changes
Спасибо. Работа принята

2023-09-06 14:52 UTC, merged