feat: MEM-50 service-worker
egoryan8/memory-game pull request #24
Opened 2023-09-07 07:43 UTC by iterrait

### Какую задачу решаем
https://linear.app/memory-game/issue/MEM-50/dobavit-service-workers
Необходимо подключить service worker

2023-09-07 07:52 UTC, thevolkov commented on packages/client/public/service-worker.js
> +      .catch((err) => {
Лучше наверно try/catch как во всем проекте

2023-09-07 08:10 UTC, aip-webdev approved these changes

2023-09-07 08:16 UTC, thevolkov approved these changes

2023-09-07 08:17 UTC, iterrait commented on packages/client/public/service-worker.js
> +      .catch((err) => {
ESlint говорит, что лишняя обертка try/cath и в материалах урока было без него.

2023-09-07 19:31 UTC, Olegas requested changes
Добрый день. 
Есть пара ошибок в коде - написал комментарии.
Нужно доработать

2023-09-07 19:31 UTC, Olegas commented on packages/client/public/service-worker.js
> +        .filter(() => false)
Странная конструкция. Она просто отфильтрует все записи массива. Дальнейшие действия будут бесполезны.

2023-09-07 19:31 UTC, Olegas commented on packages/client/public/service-worker.js
> +          if (!response || response.status > 500) {
Думаю тут хотели >= 500?

2023-09-08 01:01 UTC, iterrait commented on packages/client/public/service-worker.js
> +          if (!response || response.status > 500) {
Поправила

2023-09-08 06:18 UTC, Olegas commented on packages/client/public/service-worker.js
> +      .catch((err) => {
Кстати, тоже обратил внимание - тут вообще странная конструкция. Зачем catch которы внутри делает throw? Если мы хотели обработать ошибку и даже в случае ошибки продолжить работу, то throw нам не нужен. А при текущей реализации получается что мы поймали ошибку и сразу же ее выкинули обратно - можно просто catch убрать

2023-09-08 06:19 UTC, Olegas requested changes
Есть вопрос по коду - обработка ошибок в событии install

2023-09-08 06:51 UTC, iterrait commented on packages/client/public/service-worker.js
> +      .catch((err) => {
Убрала catch.

Но данная конструкция была взята из материалов урока: https://disk.yandex.ru/i/hZxWs8Bu3-VkpQ

2023-09-08 06:55 UTC, iterrait commented
Убрала catch.

Но данная конструкция была взята из материалов урока: https://disk.yandex.ru/i/hZxWs8Bu3-VkpQ

2023-09-09 14:19 UTC, Olegas commented
@iterrait да, верно, в уроке такая конструкция. Но у нее есть смысл - там кроме throw err есть еще вывод ошибки в консоль. А у тебя его не было. И получилось что конструкция не имела смысла.

2023-09-09 14:19 UTC, Olegas approved these changes
Работ принята

2023-09-09 14:30 UTC, iterrait commented
> @iterrait да, верно, в уроке такая конструкция. Но у нее есть смысл - там кроме throw err есть еще вывод ошибки в консоль. А у тебя его не было. И получилось что конструкция не имела смысла.

Понятно, спасибо

2023-09-09 14:34 UTC, merged