feat: MEM-57 Add yandex oAuth
egoryan8/memory-game pull request #34
Opened 2023-09-29 02:58 UTC by thevolkov

### Таска: https://linear.app/memory-game/issue/MEM-57/dobavit-oauth-avtorizaciyu-v-proekt
Авторизация с помощью yandex Oauth

2023-09-29 18:50 UTC, aip-webdev approved these changes

2023-09-29 20:50 UTC, manshind requested changes
Оставил пару важных комментариев

2023-09-29 20:50 UTC, manshind commented on packages/client/src/pages/Login/Login.tsx
> +  const redirectUri = 'http://localhost:3000'
такой путь будет работать только при локальной разработке, для продакшена его нужно менять.
это можно сделать либо через задание переменных окружения, либо собирать из window.location (для этого варианта нужны будут дополнительные проверки, что код запускается на клиенте, если у вас есть ssr).

2023-09-29 20:50 UTC, manshind commented on packages/client/src/pages/Login/Login.tsx
> +    if (!authCode) return
если у вас проверка на authCode происходит на странице логина, то и в качестве redirectUri стоит указать путь до страницы логина (сейчас redirectUri ведет на главную)

2023-10-01 23:21 UTC, thevolkov commented on packages/client/src/pages/Login/Login.tsx
> +  const redirectUri = 'http://localhost:3000'
добавил вариант через window.location.origin, но ssr у нас пока нет. Поэтому до этого указал http://localhost:3000

2023-10-01 23:24 UTC, thevolkov commented on packages/client/src/pages/Login/Login.tsx
> +    if (!authCode) return
Я сделал страницу логина главной чтобы авторизация работала. Только http://localhost:3000 зарегистрирован как callback_url в практикуме. В противном случае не работает. После того как у нас появиться свой домен, зарегистрирую в яндекс авторизации свое приложения и сделаем сallback_url как нужно, пока что так

2023-10-02 10:51 UTC, McReign commented on packages/client/src/pages/Login/Login.tsx
> +  const redirectUri = 'http://localhost:3000'
👍

2023-10-02 10:52 UTC, McReign approved these changes

2023-10-02 10:55 UTC, merged