feat: MEM-66_themes-backend
egoryan8/memory-game pull request #47
Opened 2023-10-14 17:47 UTC by Tailler1992

### Переключение тем (серверная часть)

2023-10-14 21:10 UTC, thevolkov approved these changes

2023-10-15 07:55 UTC, Olegas requested changes
Добрый день.
Есть замечания по коду. Написал комментарии отдельно по всем непонятным местам.
Нужно доработать

2023-10-15 07:55 UTC, Olegas commented on db/db-init/initial.sql
> +    user_id integer                                  NOT NULL,
Думаю здесь не хватает уникального индекса на поле user_id. Если его не сделать, у одного пользователя может оказаться несколько записей с темами

2023-10-15 07:55 UTC, Olegas commented on packages/server/services/theme/theme.ts
> +  if (req.headers.cookie) {
Очень странная проверка. То есть получается просто наличие хоть каких-то cookies считается достаточной для того, что бы считать пользователя авторизованным?

2023-10-15 07:55 UTC, Olegas commented on packages/server/services/theme/theme.ts
> +    const { theme, user_id } = req.body
У вас уже есть middleware, которая проверяет авторизацию? Если да, то в ней уже есть данные о реальном авторизованном пользователе. Надо брать данные оттуда, а не из тела запроса. Иначе я смогу менять тему другому пользователю просто зная его id

2023-10-15 07:55 UTC, Olegas commented on packages/server/services/theme/theme.ts
> +export const createPost: Handler = async (req, res) => {
Post? Тут же про темы?

2023-10-15 07:55 UTC, Olegas commented on db/db-init/initial.sql
> +       (2, 1333365, 'light');
Как это может быть - один пользователь и две темы оформления?

2023-10-15 07:55 UTC, Olegas commented on packages/server/services/theme/theme.ts
> +export const allTheme: Handler = async (req, res) => {
Зачем может понадобиться на стороне фронта знать все настройки тем всех пользователей?

2023-10-15 07:55 UTC, Olegas commented on packages/server/services/theme/theme.ts
> +    })
Когда у вас появится уникальный индекс по user_id, что бы избежать проблем при конкурентных запросах, здесь нужно использовать подход upsert вместо просто create

2023-10-15 07:55 UTC, Olegas commented on packages/server/services/theme/theme.ts
> +}
А как получить тему для текущего пользователя? Явно не хватает еще одного метода

2023-10-15 12:48 UTC, Tailler1992 commented on packages/server/services/theme/theme.ts
> +    const { theme, user_id } = req.body
middleware еще нет, добавим на неделе доработок

2023-10-15 15:52 UTC, Olegas approved these changes
Работа принята

2023-10-15 15:57 UTC, merged